remote_theme: just-the-docs/just-the-docs
title: VE3NEA's Tech Notes
description: Ham projects by VE3NEA
aux_links:
  "VE3NEA' Projects on GitHub": "https://github.com/VE3NEA"
  "VE3NEA' Projects on dxatlas.com": "https://dxatlas.com"
